CREATE TABLE SVM.USAGESTATISTICTASK
(
  IKODUSAGESTATISTICTASK  NUMBER                NOT NULL,
  NVCLOGIN                VARCHAR2(32 CHAR)     DEFAULT USER                  NOT NULL,
  NVCHOST                 VARCHAR2(128 CHAR)    DEFAULT trim(sys_context('USERENV', 'HOST')) NOT NULL,
  DTEVENT                 DATE                  DEFAULT sysdate               NOT NULL,
  IKODTREETASK            NUMBER                NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE SVM.USAGESTATISTICTASK IS 'Таблица сбора статистики по событиям задач. Сейчас только запуск задачи';

COMMENT ON COLUMN SVM.USAGESTATISTICTASK.IKODUSAGESTATISTICTASK IS 'ID';

COMMENT ON COLUMN SVM.USAGESTATISTICTASK.NVCLOGIN IS 'Кто инициировал событие (имя пользователя)';

COMMENT ON COLUMN SVM.USAGESTATISTICTASK.NVCHOST IS 'Где произошло событие (компьютер)';

COMMENT ON COLUMN SVM.USAGESTATISTICTASK.DTEVENT IS 'Дата и время наступления события';

COMMENT ON COLUMN SVM.USAGESTATISTICTASK.IKODTREETASK IS 'ID задачи';


CREATE INDEX SVM.IDX_USAGESTATTASK_USERDATA ON SVM.USAGESTATISTICTASK
(NVCLOGIN, DTEVENT)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX SVM.USAGESTATISTICTASK_PK ON SVM.USAGESTATISTICTASK
(IKODUSAGESTATISTICTASK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE SEQUENCE SVM.SQ_USAGESTATISTICTASK
  START WITH 21
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


GRANT SELECT ON SVM.SQ_USAGESTATISTICTASK TO TESTDBROLE1;


CREATE OR REPLACE TRIGGER SVM.TR_BI_USAGESTATISTICTASK
BEFORE INSERT
ON SVM.USAGESTATISTICTASK
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column IKODUSAGESTATISTICTASK
  :new.IKODUSAGESTATISTICTASK := SQ_USAGESTATISTICTASK.nextval;
END TR_BI_USAGESTATISTICTASK;
/


ALTER TABLE SVM.USAGESTATISTICTASK ADD (
  CONSTRAINT USAGESTATISTICTASK_PK
  PRIMARY KEY
  (IKODUSAGESTATISTICTASK)
  USING INDEX SVM.USAGESTATISTICTASK_PK
  ENABLE VALIDATE);

ALTER TABLE SVM.USAGESTATISTICTASK ADD (
  CONSTRAINT FK_USAGESTATISTICTASK_TASK 
  FOREIGN KEY (IKODTREETASK) 
  REFERENCES SVM.STREETASK (IKODTREETASK)
  ON DELETE CASCADE
  ENABLE VALIDATE);

GRANT SELECT ON SVM.USAGESTATISTICTASK TO TESTDBROLE1;
